### ISSUE TITLE
OV7670 webserver images

### ISSUE THREAD

**Issue by adellari** [tekker/esp32-ov7670-hacking#6]
Hello Tekker, I have been following this post since igrr's original post on the camera and the esp32. I was massively delighted to see you have been able to get the ov7670 working with the esp32. I am looking to view the images through a webpage served up by the esp instead of a display. If you can point me to the variables that contain the image data or where it is stored, I would love to work on achieving this. I have been looking through the code but am still unsure as to where the actual image data is stored. Would you be willing to help me out? I am pursuing this for a larger project that I am working on. Thank you for your work already.

**Comment by tekker** [comment]
The way it works at the moment is that an image stream is requested from the browser ie, via http://10.0.0.118/stream which triggers a call to capture the OV7670 sensor, this is then rendered as a .BMP bitmap file, and displayed in the browser.  The HTTP request also triggers an update to the LCD display.  If you just want a single image, you can use http://10.0.0.118/bmp which just takes one image, sends the .BMP file to the browser, and displays it in the LCD.  If you want the "raw" capture from the OV7670, you can use http://10.0.0.118/get.  At the moment YUV422 and RGB565 modes are supported.  To change settings on the fly you can telnet in to the ESP32 (telnet 10.0.0.118) and type "help" to get a list of commands.  The first command to try is "colorbar 0" which turns off the Test Pattern output, and maybe "pixformat rgb565" to switch the sensor mode.

**Comment by adellari** [comment]
So if I were to take out the segments that prep the inage for the display, that would speed up the webservee's response time?
