### ISSUE TITLE
No response on SCCB interface

### ISSUE THREAD

**Issue by mic159** [tekker/esp32-ov7670-hacking#9]
I'm having trouble getting my OV7670 (without FIFO) camera to work with my LOLIN32 board.
It's always returning 0 when I run `SCCB_Probe()`

My connections are:

OV7670 | ESP32
--------- | ----------
GND | GND
3.3v | 3.3v
PWDN | GND (via 10kΩ)
XCLK | 18
PWDN | 5
SIOC | SCL (22)
SIOD | SDA (21)

Everything else is floating.

I can confirm a 10 MHZ signal on XCLK, and I can see some other frequencies on the PCLK, HREF and VSYNC pins.

I moved the code into a standalone program to attempt to debug, but I cant seem to get it to work.
The code is here: https://gist.github.com/mic159/c80494c7be5034150e29d21b0388d5a6

Is there something obvious I'm doing wrong, or is my module broken?

**Comment by tekker** [comment]
Hi mic159 - maybe double check the PWDN signal is all I can think of (or try pulling it high).

**Comment by mic159** [comment]
I tried pulling it high, and still no luck.
Maybe my module is broken :( Ordered another, will see how it goes.

**Comment by mic159** [comment]
Woo, got a new module in today, and its all working!
Phew, it was just a broken module.
